main:
    -
        label: Accueil
        title: ''
        path: accueil
        class: first
        submenu:
            -
                label: 'Sub 1'
                path: entry/2
    -
        label: 'The Bolt site'
        link: 'http://bolt.cm'
        class: last
    -
        label: 'Second item'
        path: entry/1
        submenu:
            -
                label: 'Sub 4'
                class: sub-class
                path: page/3
            -
                label: 'Sub 2'
                class: menu-item-class
                path: entry/3
            -
                label: 'Sub 3'
                path: entry/4
    -
        label: 'All pages'
        path: pages/
